*Note :  ctrl+ shift +k for Table of contents* 

# Numpy Introduction 
## What is Numpy? 
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python list.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very esy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists? 

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4]) # array created using list 
arr2 = np.array((4,5,6,7)) # array created using tuple 
print(arr)
print(arr2)
print(type(arr))
print(type(arr2))

[1 2 3 4]
[4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Checking numpy version

In [10]:
np.__version__

'1.26.4'

# Dimensions in array

*A dimension in arrays is one level of array depth (nested arrays).* 

In [5]:
# 0-D array 
arr = np.array(42)
print(arr)

42


In [7]:
# 1-D array 
arr = np.array([1,23,56,13])
print(arr)

[ 1 23 56 13]


In [9]:
# 2-D array 
arr = np.array([[1,2,3],[9,2,3]])
print(arr)

[[1 2 3]
 [9 2 3]]


In [19]:
# 3-D array 
arr =np.array([[[1,2,3], [2,3,4], [3,5,6]]])
print(arr) 

[[[1 2 3]
  [2 3 4]
  [3 5 6]]]


# Checking the number of dimensions 

In [32]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


# .size gives number of elements in an array 

print('Size of arrays :') 
print(a.size)
print(b.size)
print(c.size)
print(d.size)


0
1
2
3
Size of arrays :
1
5
6
12


# Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [23]:
arr = np.array ([1,2,3],ndmin =5)
print(arr)

[[[[[1 2 3]]]]]


# Array Indexing in Numpy

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


# Get Shape

In [3]:
# shape(r,c)
arr.shape

(4,)

# Get Datatype

In [9]:
a = np.array([1,2,3,4])
b = np.array([1.1,2.2,3.3])
print(a.dtype)
print(b.dtype)

int32
float64


# Get Size 

In [15]:
arr2 = np.array([10,20,30,30])
print(arr2.itemsize)

4


NOTE: itemsize() function Returns size of each element in bytes present in array

# Get total Size

In [17]:
arr = np.array([10,20,30,40,50])
arr.size

5

# Accessing/Changing specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


##  Get specific element [r,c]

In [20]:
a[1,5]

13

## Get specific row 

In [22]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

## Get specific columns

In [24]:
a[:,2]

array([ 3, 10])

## Getting a little more fancy [start_index : end_index : step_size]

In [26]:
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-D Example

In [30]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


## Get specific element (work outside in)

In [31]:
b[0,1,1]

4

In [34]:
b[:, 1, :] = [[9, 9]]


In [35]:
b

array([[[1, 2],
        [9, 9],
        [5, 6],
        [7, 8]]])

# Initializing Different Types of Arrays


## All 0s matrix

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## All 1s matrix 

In [39]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

# Any other number

In [71]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

# Any other number (full_like)

In [72]:
np.full_like(a, 4)

array([[4., 4., 4.],
       [4., 4., 4.]])

# Random decimal numbers

In [73]:
np.random.rand(4,2)

array([[0.60840847, 0.20892639],
       [0.6627749 , 0.66158869],
       [0.12907081, 0.80559881],
       [0.97859571, 0.47357269]])

# Random Integer values

In [74]:
np.random.randint(-4,8, size=(3,3))

array([[ 7,  7,  4],
       [ 3,  5,  2],
       [ 0,  3, -4]])

# The identity matrix

In [ ]:
np.identity(5)

# Repeat an array

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [46]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [50]:
a + 2

array([3, 4, 5, 6])

In [51]:
a-2

array([-1,  0,  1,  2])

In [52]:
a*2

array([2, 4, 6, 8])

In [53]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [54]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [55]:
a**2

array([ 1,  4,  9, 16])

In [56]:
# Take the sin 
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### For a lot more [https://docs.scipy.org/doc/numpy/reference/routines.math.html]

# Linear Algebra

In [59]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b) # matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [60]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(stats)

1

In [63]:
np.max(stats, axis=1)

array([3, 6])

In [64]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4, 2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

## Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))

# Creating arrays from Python's sequence types

In [75]:
squares = [x**2 for x in range(10)] # python list
cubes = tuple(x**3 for x in range(10)) # python tuple
evens = {x for x in range(10) if x%2 == 0} # python set
print(type(squares))
print(type(cubes))
print(type(evens))

<class 'list'>
<class 'tuple'>
<class 'set'>


In [77]:
a = np.array(squares)
b = np.array(cubes)
c = np.array(evens)
if type(a) == type(b) == type(c):
    print(type(a))

<class 'numpy.ndarray'>


In [78]:
seq2 = [[x, x**2, x**3] for x in range(10)]
seq3 = [[[x for x in range(3)], [y for y in range(3, 6)]] for z in range(10)]
a = np.array(seq2) # create array from nested lists of depth 2
b = np.array(seq3) # create array from nested lists of depth 3
print(a.ndim)
print(b.ndim)

2
3


In [79]:
odds = list(i for i in range(10) if i%2 != 0)
numpy_odds = np.array(odds, dtype=complex) # declare data type during instantiation
numpy_odds

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])

In [80]:
zeros = np.zeros((3, 3), dtype=np.int32) # create a 3x3 array of 0's
ones = np.ones((2, 2), dtype=np.float64) # create a 2x2 array of 1's
empty = np.empty((3, 3))
print(zeros, zeros.dtype.name)
print(ones, ones.dtype.name)
print(empty, empty.dtype.name)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32
[[1. 1.]
 [1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64


In [81]:
a = np.arange(5, 30, 5) # create array from range [5, 30) with step of 5
a

array([ 5, 10, 15, 20, 25])

In [82]:
b = np.linspace(0, 1, 100) # create array of 100 values between 0 and 1
b

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [85]:
from numpy import pi
c = np.linspace(0, 2*pi, 10)# useful for evaluating trigonometric function
f = np.sin(c)
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [87]:
# creating an array from a function
def f(row_num, col_num):
    return 2*row_num + col_num
F = np.fromfunction(f, (3, 3), dtype=int)
F

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

# Printing arrays

In [88]:
dim1 = np.arange(15) # Create 1 1x15 matrix; n=1
dim2 = np.arange(15).reshape(3, 5) # Create 1 3x5 matrix; n=2
dim3 = np.arange(24).reshape(2, 3, 4) # Create 2 3x4 matrices; n=3
print(dim1, end='\t[1x15]\n\n')
print(dim2, end='\t[3x5]\n\n')
print(dim3, end='\t[2x3x4]')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]	[1x15]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]	[3x5]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]	[2x3x4]

In [89]:
very_large = np.arange(10000).reshape(100, 100)
print(very_large) # printing a very large array

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Common NumPy array operations
- Arithmetic operators on arrays apply elementwise.
- A new array is created and filled with the result.

In [90]:
a = np.arange(10)
b = np.array([2 for x in range(10)])
c = np.ones(10, dtype=int)
result = a + b - c # add 2 and subtract 1 from each element of a
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [91]:
result **= 2 # square each element of result
result

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
result < 10

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [93]:
a = np.ones(15).reshape(3, 5)
b = np.ones(15).reshape(5, 3)
mult = a * 10 # element-wise multiplication
dot_prod1 = a.dot(b) # dot product version 1
dot_prod2 = np.dot(a, b) # dot product version 2
print(mult, end='\n\n')
print(dot_prod1, end='\n\n')
print(dot_prod2)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [94]:
a, b = dot_prod1, dot_prod2
a += b # += and *= act in place -- they modify the existing array
a

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [95]:
# array operations result in upcasting (result is more general type)
a = np.ones(10, dtype=int)
b = np.ones(10, dtype=float)
c = np.ones(10, dtype=complex)
a_plus_b = a + b # int + float
b_plus_c = b + c # float + complex
print(a_plus_b.dtype.name)
print(b_plus_c.dtype.name)

float64
complex128


In [96]:
# useful array methods
a = np.arange(1, 11)
print('Sum:', a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 55
Min: 1
Max: 10


In [97]:
# applying methods to a single axis
a = np.arange(15).reshape(3, 5) + 1
print(a.sum(axis=0)) # sum each column
print(a.min(axis=1)) # min of each row
a

[18 21 24 27 30]
[ 1  6 11]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Universal functions

In [98]:
# universal functions (sin, cos, exp, sqrt, ... etc)
a = np.linspace(0, 2*pi, 10000)
sin_a = np.sin(a)
sqrt_a = np.sqrt(a)
exp_a = np.exp(a)
print(sin_a, end='\n\n')
print(sqrt_a, end='\n\n')

[ 0.00000000e+00  6.28381328e-04  1.25676241e-03 ... -1.25676241e-03
 -6.28381328e-04 -2.44929360e-16]

[0.         0.02506754 0.03545085 ... 2.50637757 2.50650293 2.50662827]



# Indexing, slicing, and iterating


In [99]:
# slicing NumPy arrays
cubes = np.arange(1, 13).reshape(4, 3)**3 # cubes of 1-12
print(cubes[:,:], end='\n\n') # all rows, all cols
print('First Column:\t', cubes[:, 0]) # first col
print('Last Column:\t', cubes[:, -1]) # last col
print('First Row:\t', cubes[0, :]) # first row

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]]

First Column:	 [   1   64  343 1000]
Last Column:	 [  27  216  729 1728]
First Row:	 [ 1  8 27]


In [100]:
# iterating through array elements
A = np.array([x+1 for x in range(10)])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
for a in A:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,

In [104]:
A = A.reshape(2, 5)
for a in A[0,:]: # for element in row 1
    print(a**2, end=',')

1,4,9,16,25,

In [105]:
# Advanced: using ... for axis completion
A = np.arange(125).reshape(5, 5, 5) + 1
print('A[0, ...] == A[0, :, :]', end='\n\n')
print(A[0, ...], '\n\n', A[0, :, :])

A[0, ...] == A[0, :, :]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [107]:
# flattening a 5x5x5 array for iteration
for a in A.flat:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,

# Shape manipulation

## Changing the shape of an array 

In [108]:
a = np.floor(10*np.random.random((3, 4)))
print(a)
print(a.shape)

[[6. 5. 1. 9.]
 [4. 4. 6. 1.]
 [8. 4. 4. 6.]]
(3, 4)


In [109]:
a.ravel() # returns a COPY of the array flattened

array([6., 5., 1., 9., 4., 4., 6., 1., 8., 4., 4., 6.])

In [110]:
a.reshape(6, 2) # returns a COPY of the array reshaped

array([[6., 5.],
       [1., 9.],
       [4., 4.],
       [6., 1.],
       [8., 4.],
       [4., 6.]])

In [111]:
a.T # returns a COPY of the array, transposed

array([[6., 4., 8.],
       [5., 4., 4.],
       [1., 6., 4.],
       [9., 1., 6.]])

In [112]:
print('A:\t', a.shape)
print('A^T:\t', a.T.shape)

A:	 (3, 4)
A^T:	 (4, 3)


In [114]:
A = np.floor(10*np.random.random((3, 4)))
A.reshape(4, 3) # reshape returns a COPY of A
print(A, 'array A remains unchanged')
A.resize(4, 3) # resize modifies array A
print(A, 'array A is of a new shape')


[[0. 5. 8. 2.]
 [9. 2. 9. 5.]
 [1. 5. 7. 3.]] array A remains unchanged
[[0. 5. 8.]
 [2. 9. 2.]
 [9. 5. 1.]
 [5. 7. 3.]] array A is of a new shape


## Stacking NumPy arrays horizontally and vertically

In [115]:
a = np.zeros(9, dtype=int).reshape(3, 3)
b = np.ones(9, dtype=int).reshape(3, 3)
# stack horizontally:
hor = np.hstack((a, b))
ver = np.vstack((a, b))
print('a:\n', a)
print('b:\n', b)
print('Horizontal Stack:\n', hor)
print('Vertical Stack:\n', ver)

a:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
b:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Horizontal Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Vertical Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [116]:
# similarly, row_stack and column_stack can be used to stack into 2D arrays
r_stack = np.row_stack((a, b))
c_stack = np.column_stack((a, b))
print('Horizontal Stack:\n', hor)
print('Vertical Stack:\n', ver)
print('Column Stack:\n', c_stack)
print('Row Stack:\n', r_stack)

Horizontal Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Vertical Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Column Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Row Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [117]:
# use range literals to concatenate arrays on the fly
np.r_[1:5, 5, 6:10, 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

## Splitting large arrays into smaller ones

In [119]:
# use hsplit or vsplit to split arrays
a = np.ones(9).reshape(3, 3)
a_1, a_2, a_3 = np.hsplit(a, 3) # split a into 3 arrays
print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')
print(a_3, end='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]



# Views and copies

## No copy at all

In [121]:
a = np.arange(15).reshape(5, 3)
b = a
a is b

True

## View or shallow copy

In [123]:
# use the view() method to create a shallow copy of an array
a = np.array([x**2 for x in range(6)])
b = a.view()
print('a is b:', a is b)
print('a is b.base:', a is b.base)
b.shape = 3, 2
print(a.shape, ': no change to a\'s shape') # a's shape doesn't change
b[0, 1] = 1000
print(a, 'a\'s data has changed!')

a is b: False
a is b.base: True
(6,) : no change to a's shape
[   0 1000    4    9   16   25] a's data has changed!


# Deep copy

In [124]:
a = np.array([x+1 for x in range(10)])
b = a.copy()
print('a:', a, end='\t(Original)\n\n')
print('b:', b, end='\t(Deep Copy)\n\n')
print('a is b:', a is b)

a: [ 1  2  3  4  5  6  7  8  9 10]	(Original)

b: [ 1  2  3  4  5  6  7  8  9 10]	(Deep Copy)

a is b: False


# Advanced NumPy
- Fancy indexing and index tricks
- Indexing with arrays of integers and booleans

In [125]:
# arrays can be indexed by arrays of integers and arrays of booleans
squares = np.array([(x)**2 for x in range(10)])
evens = np.array([x for x in range(10) if x%2 == 0])
odds = np.array([False if x%2 == 0 else True for x in range(10)])
squares_of_evens = squares[evens]
squares_of_odds = squares[odds]
print('Indexing with array of Ints:\t', squares_of_evens)
print('Indexing with array of Bools:\t', squares_of_odds)

Indexing with array of Ints:	 [ 0  4 16 36 64]
Indexing with array of Bools:	 [ 1  9 25 49 81]


# The ix_() function

In [127]:
# use ix_() to compute all a + b*c pairs for matrices a, b, and c
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
ax, bx, cx = np.ix_(a, b, c)
f = ax + bx*cx
if f[2, 1, 0] == a[2]+b[1]*c[0]:
    print(f)

[[[29 33 37]
  [36 41 46]
  [43 49 55]]

 [[30 34 38]
  [37 42 47]
  [44 50 56]]

 [[31 35 39]
  [38 43 48]
  [45 51 57]]]
